### ISSUE TITLE
Meaning of coding and codec

### ISSUE THREAD

**Issue by dtlnor** [iAvoe/x264-web-tutorial#1]
https://github.com/iAvoe/x264-web-tutorial/blob/8241c07b70ac98e7e69e1f040c58de814f0cf9c8/HTML/index.html#L755

*coding* means [Computer programming](https://en.wikipedia.org/wiki/Computer_programming). (编程)

*[Source coding](https://en.wikipedia.org/wiki/Data_compression)* aka data compression is the process of encoding information using fewer bits than the original representation. (信源编码)

*[codec](https://en.wikipedia.org/wiki/Codec)* is a portmanteau of coder/decoder. (编解码器)
  or specifically, A [video codec](https://en.wikipedia.org/wiki/Video_codec) is software or hardware that compresses and decompresses digital video.

*编码* in english is [encoding](https://en.wikipedia.org/wiki/Code) or code.
  or specifically, [video encoding](https://en.wikipedia.org/wiki/Data_compression#Video)

**Comment by iAvoe** [comment]
省略性错误：“编码标准”在中文里一般简称为“编码”，导致了误解。修复：e9828bb
