### ISSUE TITLE
Ambiguous description about color range

### ISSUE THREAD

**Issue by dtlnor** [iAvoe/x264-web-tutorial#2]
https://github.com/iAvoe/x264-web-tutorial/blob/b73c30e03dbeba2b1d598a1d917af57d9aa45d01/HTML/index.html#L160
ref conversation: https://github.com/iAvoe/x264-web-tutorial/commit/3bd3dbded5032e53dd82956cce69962a02635b36#r143490375

**Comment by iAvoe** [comment]
This issue was fixed, closing
